version: 'latest'

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rmq
  
  manager:
    image: main
    build:
      context: ./
      dockerfile: ./manager/Dockerfile
    networks:
      - rmq
    stdin_open: true
    tty: true
    depends_on:
      - rabbitmq

  worker:
    image: worker
    build:
      context: ./
      dockerfile: ./worker/Dockerfile
    networks:
      - rmq
    stdin_open: true
    tty: true
    deploy:
    ### Change this value to upscale number of workers
      replicas: 2
    depends_on:
      - rabbitmq

  outputter:
    image: output
    build:
      context: ./
      dockerfile: ./outputter/Dockerfile
    volumes:
      - .:/app/data_storage
    networks:
      - rmq
    stdin_open: true
    tty: true
    depends_on:
      - rabbitmq

networks:
  rmq:
    driver: bridge

